"""Contains all the data models used in inputs/outputs"""

from .abstract_response import AbstractResponse
from .available_sources_response import AvailableSourcesResponse
from .backfill import Backfill
from .backfill_response import BackfillResponse
from .backfill_response_meta import BackfillResponseMeta
from .backfill_status import BackfillStatus
from .change_transfer_state_request import ChangeTransferStateRequest
from .change_transfer_state_request_transfer_state import ChangeTransferStateRequestTransferState
from .change_transfer_state_response_400 import ChangeTransferStateResponse400
from .change_transfer_state_response_400_meta import ChangeTransferStateResponse400Meta
from .change_transfer_state_response_401 import ChangeTransferStateResponse401
from .change_transfer_state_response_401_meta import ChangeTransferStateResponse401Meta
from .change_transfer_state_response_403 import ChangeTransferStateResponse403
from .change_transfer_state_response_403_meta import ChangeTransferStateResponse403Meta
from .change_transfer_state_response_404 import ChangeTransferStateResponse404
from .change_transfer_state_response_404_meta import ChangeTransferStateResponse404Meta
from .change_transfer_state_response_429 import ChangeTransferStateResponse429
from .change_transfer_state_response_429_meta import ChangeTransferStateResponse429Meta
from .change_transfer_state_response_500 import ChangeTransferStateResponse500
from .change_transfer_state_response_500_meta import ChangeTransferStateResponse500Meta
from .close_login_link_response_401 import CloseLoginLinkResponse401
from .close_login_link_response_401_meta import CloseLoginLinkResponse401Meta
from .close_login_link_response_404 import CloseLoginLinkResponse404
from .close_login_link_response_404_error import CloseLoginLinkResponse404Error
from .close_login_link_response_422 import CloseLoginLinkResponse422
from .close_login_link_response_422_meta import CloseLoginLinkResponse422Meta
from .close_login_link_response_429 import CloseLoginLinkResponse429
from .close_login_link_response_429_meta import CloseLoginLinkResponse429Meta
from .close_login_link_response_500 import CloseLoginLinkResponse500
from .close_login_link_response_500_error import CloseLoginLinkResponse500Error
from .connector import Connector
from .connector_configuration import ConnectorConfiguration
from .connector_configuration_configuration_json import ConnectorConfigurationConfigurationJson
from .connector_with_configuration import ConnectorWithConfiguration
from .create_backfill_request import CreateBackfillRequest
from .create_backfill_response_400 import CreateBackfillResponse400
from .create_backfill_response_400_meta import CreateBackfillResponse400Meta
from .create_backfill_response_401 import CreateBackfillResponse401
from .create_backfill_response_401_meta import CreateBackfillResponse401Meta
from .create_backfill_response_403 import CreateBackfillResponse403
from .create_backfill_response_403_meta import CreateBackfillResponse403Meta
from .create_backfill_response_422 import CreateBackfillResponse422
from .create_backfill_response_422_meta import CreateBackfillResponse422Meta
from .create_backfill_response_429 import CreateBackfillResponse429
from .create_backfill_response_429_meta import CreateBackfillResponse429Meta
from .create_backfill_response_500 import CreateBackfillResponse500
from .create_backfill_response_500_meta import CreateBackfillResponse500Meta
from .create_connector_body import CreateConnectorBody
from .create_connector_response_401 import CreateConnectorResponse401
from .create_connector_response_401_meta import CreateConnectorResponse401Meta
from .create_connector_response_403 import CreateConnectorResponse403
from .create_connector_response_403_meta import CreateConnectorResponse403Meta
from .create_connector_response_404 import CreateConnectorResponse404
from .create_connector_response_404_meta import CreateConnectorResponse404Meta
from .create_connector_response_429 import CreateConnectorResponse429
from .create_connector_response_429_meta import CreateConnectorResponse429Meta
from .create_connector_response_500 import CreateConnectorResponse500
from .create_connector_response_500_meta import CreateConnectorResponse500Meta
from .create_connector_secret_response_201 import CreateConnectorSecretResponse201
from .create_connector_secret_response_400 import CreateConnectorSecretResponse400
from .create_connector_secret_response_400_meta import CreateConnectorSecretResponse400Meta
from .create_connector_secret_response_401 import CreateConnectorSecretResponse401
from .create_connector_secret_response_401_meta import CreateConnectorSecretResponse401Meta
from .create_connector_secret_response_403 import CreateConnectorSecretResponse403
from .create_connector_secret_response_403_meta import CreateConnectorSecretResponse403Meta
from .create_connector_secret_response_404 import CreateConnectorSecretResponse404
from .create_connector_secret_response_404_meta import CreateConnectorSecretResponse404Meta
from .create_connector_secret_response_409 import CreateConnectorSecretResponse409
from .create_connector_secret_response_409_meta import CreateConnectorSecretResponse409Meta
from .create_connector_secret_response_422 import CreateConnectorSecretResponse422
from .create_connector_secret_response_422_meta import CreateConnectorSecretResponse422Meta
from .create_connector_secret_response_429 import CreateConnectorSecretResponse429
from .create_connector_secret_response_429_meta import CreateConnectorSecretResponse429Meta
from .create_connector_secret_response_500 import CreateConnectorSecretResponse500
from .create_connector_secret_response_500_meta import CreateConnectorSecretResponse500Meta
from .create_data_source_connection_request import CreateDataSourceConnectionRequest
from .create_data_source_connection_response import CreateDataSourceConnectionResponse
from .create_data_source_connection_response_400 import CreateDataSourceConnectionResponse400
from .create_data_source_connection_response_400_meta import CreateDataSourceConnectionResponse400Meta
from .create_data_source_connection_response_401 import CreateDataSourceConnectionResponse401
from .create_data_source_connection_response_401_meta import CreateDataSourceConnectionResponse401Meta
from .create_data_source_connection_response_403 import CreateDataSourceConnectionResponse403
from .create_data_source_connection_response_403_meta import CreateDataSourceConnectionResponse403Meta
from .create_data_source_connection_response_422 import CreateDataSourceConnectionResponse422
from .create_data_source_connection_response_422_meta import CreateDataSourceConnectionResponse422Meta
from .create_data_source_connection_response_429 import CreateDataSourceConnectionResponse429
from .create_data_source_connection_response_429_meta import CreateDataSourceConnectionResponse429Meta
from .create_data_source_connection_response_500 import CreateDataSourceConnectionResponse500
from .create_data_source_connection_response_500_meta import CreateDataSourceConnectionResponse500Meta
from .create_login_link_body import CreateLoginLinkBody
from .create_login_link_response_401 import CreateLoginLinkResponse401
from .create_login_link_response_401_meta import CreateLoginLinkResponse401Meta
from .create_login_link_response_403 import CreateLoginLinkResponse403
from .create_login_link_response_403_error import CreateLoginLinkResponse403Error
from .create_login_link_response_422 import CreateLoginLinkResponse422
from .create_login_link_response_422_meta import CreateLoginLinkResponse422Meta
from .create_login_link_response_429 import CreateLoginLinkResponse429
from .create_login_link_response_429_meta import CreateLoginLinkResponse429Meta
from .create_login_link_response_500 import CreateLoginLinkResponse500
from .create_login_link_response_500_meta import CreateLoginLinkResponse500Meta
from .create_secret_request import CreateSecretRequest
from .create_transfer_response_400 import CreateTransferResponse400
from .create_transfer_response_400_meta import CreateTransferResponse400Meta
from .create_transfer_response_401 import CreateTransferResponse401
from .create_transfer_response_401_meta import CreateTransferResponse401Meta
from .create_transfer_response_403 import CreateTransferResponse403
from .create_transfer_response_403_meta import CreateTransferResponse403Meta
from .create_transfer_response_409 import CreateTransferResponse409
from .create_transfer_response_409_meta import CreateTransferResponse409Meta
from .create_transfer_response_422 import CreateTransferResponse422
from .create_transfer_response_422_meta import CreateTransferResponse422Meta
from .create_transfer_response_429 import CreateTransferResponse429
from .create_transfer_response_429_meta import CreateTransferResponse429Meta
from .create_transfer_response_500 import CreateTransferResponse500
from .create_transfer_response_500_meta import CreateTransferResponse500Meta
from .data_query import DataQuery
from .data_query_ds_accounts_type_2 import DataQueryDsAccountsType2
from .data_query_fields_type_2_item import DataQueryFieldsType2Item
from .data_query_settings import DataQuerySettings
from .data_response import DataResponse
from .data_response_meta import DataResponseMeta
from .data_response_meta_paginate import DataResponseMetaPaginate
from .data_response_meta_query import DataResponseMetaQuery
from .data_response_meta_query_fields_item import DataResponseMetaQueryFieldsItem
from .data_response_meta_query_settings import DataResponseMetaQuerySettings
from .data_response_meta_result import DataResponseMetaResult
from .data_source import DataSource
from .data_source_connection import DataSourceConnection
from .data_source_info import DataSourceInfo
from .data_source_login import DataSourceLogin
from .data_source_login_type import DataSourceLoginType
from .data_source_type import DataSourceType
from .datasource_details import DatasourceDetails
from .datasource_details_account_labels_type_0 import DatasourceDetailsAccountLabelsType0
from .datasource_details_categories_item import DatasourceDetailsCategoriesItem
from .datasource_details_response import DatasourceDetailsResponse
from .datasource_details_response_meta import DatasourceDetailsResponseMeta
from .datasource_details_status import DatasourceDetailsStatus
from .datasource_option import DatasourceOption
from .datasource_report_type import DatasourceReportType
from .datasource_setting import DatasourceSetting
from .datasource_setting_context import DatasourceSettingContext
from .datasource_setting_type import DatasourceSettingType
from .delete_connector_response_400 import DeleteConnectorResponse400
from .delete_connector_response_400_meta import DeleteConnectorResponse400Meta
from .delete_connector_response_401 import DeleteConnectorResponse401
from .delete_connector_response_401_meta import DeleteConnectorResponse401Meta
from .delete_connector_response_403 import DeleteConnectorResponse403
from .delete_connector_response_403_meta import DeleteConnectorResponse403Meta
from .delete_connector_response_404 import DeleteConnectorResponse404
from .delete_connector_response_404_meta import DeleteConnectorResponse404Meta
from .delete_connector_response_429 import DeleteConnectorResponse429
from .delete_connector_response_429_meta import DeleteConnectorResponse429Meta
from .delete_connector_response_500 import DeleteConnectorResponse500
from .delete_connector_response_500_meta import DeleteConnectorResponse500Meta
from .delete_connector_secret_response_401 import DeleteConnectorSecretResponse401
from .delete_connector_secret_response_401_meta import DeleteConnectorSecretResponse401Meta
from .delete_connector_secret_response_403 import DeleteConnectorSecretResponse403
from .delete_connector_secret_response_403_meta import DeleteConnectorSecretResponse403Meta
from .delete_connector_secret_response_404 import DeleteConnectorSecretResponse404
from .delete_connector_secret_response_404_meta import DeleteConnectorSecretResponse404Meta
from .delete_connector_secret_response_429 import DeleteConnectorSecretResponse429
from .delete_connector_secret_response_429_meta import DeleteConnectorSecretResponse429Meta
from .delete_connector_secret_response_500 import DeleteConnectorSecretResponse500
from .delete_connector_secret_response_500_meta import DeleteConnectorSecretResponse500Meta
from .delete_transfer_response_401 import DeleteTransferResponse401
from .delete_transfer_response_401_meta import DeleteTransferResponse401Meta
from .delete_transfer_response_403 import DeleteTransferResponse403
from .delete_transfer_response_403_meta import DeleteTransferResponse403Meta
from .delete_transfer_response_404 import DeleteTransferResponse404
from .delete_transfer_response_404_meta import DeleteTransferResponse404Meta
from .delete_transfer_response_429 import DeleteTransferResponse429
from .delete_transfer_response_429_meta import DeleteTransferResponse429Meta
from .delete_transfer_response_500 import DeleteTransferResponse500
from .delete_transfer_response_500_meta import DeleteTransferResponse500Meta
from .destination_type_settings import DestinationTypeSettings
from .destination_type_settings_auth_methods_item import DestinationTypeSettingsAuthMethodsItem
from .destination_type_settings_settings_item import DestinationTypeSettingsSettingsItem
from .error import Error
from .error_response import ErrorResponse
from .error_response_meta import ErrorResponseMeta
from .get_accounts_json import GetAccountsJson
from .get_accounts_response_200 import GetAccountsResponse200
from .get_accounts_response_200_data_item import GetAccountsResponse200DataItem
from .get_accounts_response_200_data_item_accounts_item import GetAccountsResponse200DataItemAccountsItem
from .get_accounts_response_200_meta import GetAccountsResponse200Meta
from .get_accounts_response_200_meta_query import GetAccountsResponse200MetaQuery
from .get_accounts_response_400 import GetAccountsResponse400
from .get_accounts_response_400_meta import GetAccountsResponse400Meta
from .get_accounts_response_401 import GetAccountsResponse401
from .get_accounts_response_401_meta import GetAccountsResponse401Meta
from .get_accounts_response_403 import GetAccountsResponse403
from .get_accounts_response_403_meta import GetAccountsResponse403Meta
from .get_accounts_response_422 import GetAccountsResponse422
from .get_accounts_response_422_meta import GetAccountsResponse422Meta
from .get_accounts_response_429 import GetAccountsResponse429
from .get_accounts_response_429_meta import GetAccountsResponse429Meta
from .get_accounts_response_500 import GetAccountsResponse500
from .get_accounts_response_500_meta import GetAccountsResponse500Meta
from .get_available_sources_response_401 import GetAvailableSourcesResponse401
from .get_available_sources_response_401_meta import GetAvailableSourcesResponse401Meta
from .get_available_sources_response_403 import GetAvailableSourcesResponse403
from .get_available_sources_response_403_meta import GetAvailableSourcesResponse403Meta
from .get_available_sources_response_429 import GetAvailableSourcesResponse429
from .get_available_sources_response_429_meta import GetAvailableSourcesResponse429Meta
from .get_available_sources_response_500 import GetAvailableSourcesResponse500
from .get_available_sources_response_500_meta import GetAvailableSourcesResponse500Meta
from .get_backfill_by_id_response_401 import GetBackfillByIdResponse401
from .get_backfill_by_id_response_401_meta import GetBackfillByIdResponse401Meta
from .get_backfill_by_id_response_403 import GetBackfillByIdResponse403
from .get_backfill_by_id_response_403_meta import GetBackfillByIdResponse403Meta
from .get_backfill_by_id_response_404 import GetBackfillByIdResponse404
from .get_backfill_by_id_response_404_meta import GetBackfillByIdResponse404Meta
from .get_backfill_by_id_response_429 import GetBackfillByIdResponse429
from .get_backfill_by_id_response_429_meta import GetBackfillByIdResponse429Meta
from .get_backfill_by_id_response_500 import GetBackfillByIdResponse500
from .get_backfill_by_id_response_500_meta import GetBackfillByIdResponse500Meta
from .get_connector_log_response_401 import GetConnectorLogResponse401
from .get_connector_log_response_401_meta import GetConnectorLogResponse401Meta
from .get_connector_log_response_403 import GetConnectorLogResponse403
from .get_connector_log_response_403_meta import GetConnectorLogResponse403Meta
from .get_connector_log_response_404 import GetConnectorLogResponse404
from .get_connector_log_response_404_meta import GetConnectorLogResponse404Meta
from .get_connector_log_response_429 import GetConnectorLogResponse429
from .get_connector_log_response_429_meta import GetConnectorLogResponse429Meta
from .get_connector_log_response_500 import GetConnectorLogResponse500
from .get_connector_log_response_500_meta import GetConnectorLogResponse500Meta
from .get_connector_logo_response_200 import GetConnectorLogoResponse200
from .get_connector_logo_response_401 import GetConnectorLogoResponse401
from .get_connector_logo_response_401_meta import GetConnectorLogoResponse401Meta
from .get_connector_logo_response_403 import GetConnectorLogoResponse403
from .get_connector_logo_response_403_meta import GetConnectorLogoResponse403Meta
from .get_connector_logo_response_404 import GetConnectorLogoResponse404
from .get_connector_logo_response_404_meta import GetConnectorLogoResponse404Meta
from .get_connector_logo_response_429 import GetConnectorLogoResponse429
from .get_connector_logo_response_429_meta import GetConnectorLogoResponse429Meta
from .get_connector_logo_response_500 import GetConnectorLogoResponse500
from .get_connector_logo_response_500_meta import GetConnectorLogoResponse500Meta
from .get_connector_response_400 import GetConnectorResponse400
from .get_connector_response_400_meta import GetConnectorResponse400Meta
from .get_connector_response_401 import GetConnectorResponse401
from .get_connector_response_401_meta import GetConnectorResponse401Meta
from .get_connector_response_403 import GetConnectorResponse403
from .get_connector_response_403_meta import GetConnectorResponse403Meta
from .get_connector_response_404 import GetConnectorResponse404
from .get_connector_response_404_meta import GetConnectorResponse404Meta
from .get_connector_response_429 import GetConnectorResponse429
from .get_connector_response_429_meta import GetConnectorResponse429Meta
from .get_connector_response_500 import GetConnectorResponse500
from .get_connector_response_500_meta import GetConnectorResponse500Meta
from .get_data_response_400 import GetDataResponse400
from .get_data_response_400_meta import GetDataResponse400Meta
from .get_data_response_401 import GetDataResponse401
from .get_data_response_401_meta import GetDataResponse401Meta
from .get_data_response_403 import GetDataResponse403
from .get_data_response_403_meta import GetDataResponse403Meta
from .get_data_response_422 import GetDataResponse422
from .get_data_response_422_meta import GetDataResponse422Meta
from .get_data_response_429 import GetDataResponse429
from .get_data_response_429_meta import GetDataResponse429Meta
from .get_data_response_500 import GetDataResponse500
from .get_data_response_500_meta import GetDataResponse500Meta
from .get_data_source_login_response_200 import GetDataSourceLoginResponse200
from .get_data_source_login_response_401 import GetDataSourceLoginResponse401
from .get_data_source_login_response_401_meta import GetDataSourceLoginResponse401Meta
from .get_data_source_login_response_404 import GetDataSourceLoginResponse404
from .get_data_source_login_response_404_error import GetDataSourceLoginResponse404Error
from .get_data_source_login_response_422 import GetDataSourceLoginResponse422
from .get_data_source_login_response_422_meta import GetDataSourceLoginResponse422Meta
from .get_data_source_login_response_429 import GetDataSourceLoginResponse429
from .get_data_source_login_response_429_meta import GetDataSourceLoginResponse429Meta
from .get_data_source_login_response_500 import GetDataSourceLoginResponse500
from .get_data_source_login_response_500_error import GetDataSourceLoginResponse500Error
from .get_datasource_details_response_400 import GetDatasourceDetailsResponse400
from .get_datasource_details_response_400_meta import GetDatasourceDetailsResponse400Meta
from .get_datasource_details_response_401 import GetDatasourceDetailsResponse401
from .get_datasource_details_response_401_meta import GetDatasourceDetailsResponse401Meta
from .get_datasource_details_response_404 import GetDatasourceDetailsResponse404
from .get_datasource_details_response_404_meta import GetDatasourceDetailsResponse404Meta
from .get_datasource_details_response_429 import GetDatasourceDetailsResponse429
from .get_datasource_details_response_429_meta import GetDatasourceDetailsResponse429Meta
from .get_datasource_details_response_500 import GetDatasourceDetailsResponse500
from .get_datasource_details_response_500_meta import GetDatasourceDetailsResponse500Meta
from .get_latest_backfill_response_401 import GetLatestBackfillResponse401
from .get_latest_backfill_response_401_meta import GetLatestBackfillResponse401Meta
from .get_latest_backfill_response_403 import GetLatestBackfillResponse403
from .get_latest_backfill_response_403_meta import GetLatestBackfillResponse403Meta
from .get_latest_backfill_response_429 import GetLatestBackfillResponse429
from .get_latest_backfill_response_429_meta import GetLatestBackfillResponse429Meta
from .get_latest_backfill_response_500 import GetLatestBackfillResponse500
from .get_latest_backfill_response_500_meta import GetLatestBackfillResponse500Meta
from .get_login_link_response_401 import GetLoginLinkResponse401
from .get_login_link_response_401_meta import GetLoginLinkResponse401Meta
from .get_login_link_response_404 import GetLoginLinkResponse404
from .get_login_link_response_404_error import GetLoginLinkResponse404Error
from .get_login_link_response_422 import GetLoginLinkResponse422
from .get_login_link_response_422_meta import GetLoginLinkResponse422Meta
from .get_login_link_response_429 import GetLoginLinkResponse429
from .get_login_link_response_429_meta import GetLoginLinkResponse429Meta
from .get_login_link_response_500 import GetLoginLinkResponse500
from .get_login_link_response_500_meta import GetLoginLinkResponse500Meta
from .get_transfer_options_response_401 import GetTransferOptionsResponse401
from .get_transfer_options_response_401_meta import GetTransferOptionsResponse401Meta
from .get_transfer_options_response_403 import GetTransferOptionsResponse403
from .get_transfer_options_response_403_meta import GetTransferOptionsResponse403Meta
from .get_transfer_options_response_429 import GetTransferOptionsResponse429
from .get_transfer_options_response_429_meta import GetTransferOptionsResponse429Meta
from .get_transfer_options_response_500 import GetTransferOptionsResponse500
from .get_transfer_options_response_500_meta import GetTransferOptionsResponse500Meta
from .get_transfer_response_401 import GetTransferResponse401
from .get_transfer_response_401_meta import GetTransferResponse401Meta
from .get_transfer_response_403 import GetTransferResponse403
from .get_transfer_response_403_meta import GetTransferResponse403Meta
from .get_transfer_response_404 import GetTransferResponse404
from .get_transfer_response_404_meta import GetTransferResponse404Meta
from .get_transfer_response_429 import GetTransferResponse429
from .get_transfer_response_429_meta import GetTransferResponse429Meta
from .get_transfer_response_500 import GetTransferResponse500
from .get_transfer_response_500_meta import GetTransferResponse500Meta
from .get_transfer_run_response_401 import GetTransferRunResponse401
from .get_transfer_run_response_401_meta import GetTransferRunResponse401Meta
from .get_transfer_run_response_403 import GetTransferRunResponse403
from .get_transfer_run_response_403_meta import GetTransferRunResponse403Meta
from .get_transfer_run_response_404 import GetTransferRunResponse404
from .get_transfer_run_response_404_meta import GetTransferRunResponse404Meta
from .get_transfer_run_response_429 import GetTransferRunResponse429
from .get_transfer_run_response_429_meta import GetTransferRunResponse429Meta
from .get_transfer_run_response_500 import GetTransferRunResponse500
from .get_transfer_run_response_500_meta import GetTransferRunResponse500Meta
from .list_connector_logs_response_200 import ListConnectorLogsResponse200
from .list_connector_logs_response_400 import ListConnectorLogsResponse400
from .list_connector_logs_response_400_meta import ListConnectorLogsResponse400Meta
from .list_connector_logs_response_401 import ListConnectorLogsResponse401
from .list_connector_logs_response_401_meta import ListConnectorLogsResponse401Meta
from .list_connector_logs_response_403 import ListConnectorLogsResponse403
from .list_connector_logs_response_403_meta import ListConnectorLogsResponse403Meta
from .list_connector_logs_response_429 import ListConnectorLogsResponse429
from .list_connector_logs_response_429_meta import ListConnectorLogsResponse429Meta
from .list_connector_logs_response_500 import ListConnectorLogsResponse500
from .list_connector_logs_response_500_meta import ListConnectorLogsResponse500Meta
from .list_connector_secrets_response_200 import ListConnectorSecretsResponse200
from .list_connector_secrets_response_401 import ListConnectorSecretsResponse401
from .list_connector_secrets_response_401_meta import ListConnectorSecretsResponse401Meta
from .list_connector_secrets_response_403 import ListConnectorSecretsResponse403
from .list_connector_secrets_response_403_meta import ListConnectorSecretsResponse403Meta
from .list_connector_secrets_response_404 import ListConnectorSecretsResponse404
from .list_connector_secrets_response_404_meta import ListConnectorSecretsResponse404Meta
from .list_connector_secrets_response_429 import ListConnectorSecretsResponse429
from .list_connector_secrets_response_429_meta import ListConnectorSecretsResponse429Meta
from .list_connector_secrets_response_500 import ListConnectorSecretsResponse500
from .list_connector_secrets_response_500_meta import ListConnectorSecretsResponse500Meta
from .list_connectors_response_200 import ListConnectorsResponse200
from .list_connectors_response_401 import ListConnectorsResponse401
from .list_connectors_response_401_meta import ListConnectorsResponse401Meta
from .list_connectors_response_403 import ListConnectorsResponse403
from .list_connectors_response_403_meta import ListConnectorsResponse403Meta
from .list_connectors_response_429 import ListConnectorsResponse429
from .list_connectors_response_429_meta import ListConnectorsResponse429Meta
from .list_connectors_response_500 import ListConnectorsResponse500
from .list_connectors_response_500_meta import ListConnectorsResponse500Meta
from .list_data_source_logins_response_200 import ListDataSourceLoginsResponse200
from .list_data_source_logins_response_401 import ListDataSourceLoginsResponse401
from .list_data_source_logins_response_401_meta import ListDataSourceLoginsResponse401Meta
from .list_data_source_logins_response_422 import ListDataSourceLoginsResponse422
from .list_data_source_logins_response_422_meta import ListDataSourceLoginsResponse422Meta
from .list_data_source_logins_response_429 import ListDataSourceLoginsResponse429
from .list_data_source_logins_response_429_meta import ListDataSourceLoginsResponse429Meta
from .list_data_source_logins_response_500 import ListDataSourceLoginsResponse500
from .list_data_source_logins_response_500_error import ListDataSourceLoginsResponse500Error
from .list_incomplete_backfills_response_200 import ListIncompleteBackfillsResponse200
from .list_incomplete_backfills_response_401 import ListIncompleteBackfillsResponse401
from .list_incomplete_backfills_response_401_meta import ListIncompleteBackfillsResponse401Meta
from .list_incomplete_backfills_response_403 import ListIncompleteBackfillsResponse403
from .list_incomplete_backfills_response_403_meta import ListIncompleteBackfillsResponse403Meta
from .list_incomplete_backfills_response_429 import ListIncompleteBackfillsResponse429
from .list_incomplete_backfills_response_429_meta import ListIncompleteBackfillsResponse429Meta
from .list_incomplete_backfills_response_500 import ListIncompleteBackfillsResponse500
from .list_incomplete_backfills_response_500_meta import ListIncompleteBackfillsResponse500Meta
from .list_login_links_response_200 import ListLoginLinksResponse200
from .list_login_links_response_401 import ListLoginLinksResponse401
from .list_login_links_response_401_meta import ListLoginLinksResponse401Meta
from .list_login_links_response_422 import ListLoginLinksResponse422
from .list_login_links_response_422_meta import ListLoginLinksResponse422Meta
from .list_login_links_response_429 import ListLoginLinksResponse429
from .list_login_links_response_429_meta import ListLoginLinksResponse429Meta
from .list_login_links_response_500 import ListLoginLinksResponse500
from .list_login_links_response_500_meta import ListLoginLinksResponse500Meta
from .list_transfer_runs_response_401 import ListTransferRunsResponse401
from .list_transfer_runs_response_401_meta import ListTransferRunsResponse401Meta
from .list_transfer_runs_response_403 import ListTransferRunsResponse403
from .list_transfer_runs_response_403_meta import ListTransferRunsResponse403Meta
from .list_transfer_runs_response_429 import ListTransferRunsResponse429
from .list_transfer_runs_response_429_meta import ListTransferRunsResponse429Meta
from .list_transfer_runs_response_500 import ListTransferRunsResponse500
from .list_transfer_runs_response_500_meta import ListTransferRunsResponse500Meta
from .list_transfer_runs_sort_direction import ListTransferRunsSortDirection
from .list_transfer_runs_sort_field import ListTransferRunsSortField
from .list_transfers_response_401 import ListTransfersResponse401
from .list_transfers_response_401_meta import ListTransfersResponse401Meta
from .list_transfers_response_403 import ListTransfersResponse403
from .list_transfers_response_403_meta import ListTransfersResponse403Meta
from .list_transfers_response_429 import ListTransfersResponse429
from .list_transfers_response_429_meta import ListTransfersResponse429Meta
from .list_transfers_response_500 import ListTransfersResponse500
from .list_transfers_response_500_meta import ListTransfersResponse500Meta
from .log_entry import LogEntry
from .login_link import LoginLink
from .login_link_response import LoginLinkResponse
from .login_link_response_meta import LoginLinkResponseMeta
from .login_link_status_code import LoginLinkStatusCode
from .meta import Meta
from .query_details import QueryDetails
from .response_meta import ResponseMeta
from .secret import Secret
from .transfer_account import TransferAccount
from .transfer_backfill_run_error import TransferBackfillRunError
from .transfer_configuration_request import TransferConfigurationRequest
from .transfer_configuration_response import TransferConfigurationResponse
from .transfer_configuration_response_data_source import TransferConfigurationResponseDataSource
from .transfer_configuration_response_license import TransferConfigurationResponseLicense
from .transfer_configuration_response_license_features import TransferConfigurationResponseLicenseFeatures
from .transfer_configuration_response_notification_recipients_type_0_item import (
    TransferConfigurationResponseNotificationRecipientsType0Item,
)
from .transfer_created_envelope import TransferCreatedEnvelope
from .transfer_created_response import TransferCreatedResponse
from .transfer_data_source_setting import TransferDataSourceSetting
from .transfer_destination import TransferDestination
from .transfer_destination_details_item import TransferDestinationDetailsItem
from .transfer_info_response import TransferInfoResponse
from .transfer_info_response_backfill_type_0 import TransferInfoResponseBackfillType0
from .transfer_info_response_data_source_type_0 import TransferInfoResponseDataSourceType0
from .transfer_info_response_destination_type_0 import TransferInfoResponseDestinationType0
from .transfer_list_response import TransferListResponse
from .transfer_options_response import TransferOptionsResponse
from .transfer_options_response_accounts_item import TransferOptionsResponseAccountsItem
from .transfer_options_response_data_source import TransferOptionsResponseDataSource
from .transfer_options_response_data_source_settings_item import TransferOptionsResponseDataSourceSettingsItem
from .transfer_options_response_license import TransferOptionsResponseLicense
from .transfer_options_response_logins_item import TransferOptionsResponseLoginsItem
from .transfer_options_response_schedule_options_item import TransferOptionsResponseScheduleOptionsItem
from .transfer_options_response_schemas_item import TransferOptionsResponseSchemasItem
from .transfer_options_response_segments_item import TransferOptionsResponseSegmentsItem
from .transfer_run_detail import TransferRunDetail
from .transfer_run_detail_response import TransferRunDetailResponse
from .transfer_run_item import TransferRunItem
from .transfer_run_item_type import TransferRunItemType
from .transfer_run_list_response import TransferRunListResponse
from .transfer_schedule import TransferSchedule
from .transfer_schedule_run_interval import TransferScheduleRunInterval
from .transfer_segment import TransferSegment
from .transfer_state_update_response import TransferStateUpdateResponse
from .transfer_updated_response import TransferUpdatedResponse
from .update_backfill_status_body import UpdateBackfillStatusBody
from .update_backfill_status_body_status import UpdateBackfillStatusBodyStatus
from .update_backfill_status_response_400 import UpdateBackfillStatusResponse400
from .update_backfill_status_response_400_meta import UpdateBackfillStatusResponse400Meta
from .update_backfill_status_response_401 import UpdateBackfillStatusResponse401
from .update_backfill_status_response_401_meta import UpdateBackfillStatusResponse401Meta
from .update_backfill_status_response_403 import UpdateBackfillStatusResponse403
from .update_backfill_status_response_403_meta import UpdateBackfillStatusResponse403Meta
from .update_backfill_status_response_404 import UpdateBackfillStatusResponse404
from .update_backfill_status_response_404_meta import UpdateBackfillStatusResponse404Meta
from .update_backfill_status_response_422 import UpdateBackfillStatusResponse422
from .update_backfill_status_response_422_meta import UpdateBackfillStatusResponse422Meta
from .update_backfill_status_response_429 import UpdateBackfillStatusResponse429
from .update_backfill_status_response_429_meta import UpdateBackfillStatusResponse429Meta
from .update_backfill_status_response_500 import UpdateBackfillStatusResponse500
from .update_backfill_status_response_500_meta import UpdateBackfillStatusResponse500Meta
from .update_connector_request import UpdateConnectorRequest
from .update_connector_request_configuration import UpdateConnectorRequestConfiguration
from .update_connector_request_configuration_configuration_json import (
    UpdateConnectorRequestConfigurationConfigurationJson,
)
from .update_connector_request_connector import UpdateConnectorRequestConnector
from .update_connector_response_400 import UpdateConnectorResponse400
from .update_connector_response_400_meta import UpdateConnectorResponse400Meta
from .update_connector_response_401 import UpdateConnectorResponse401
from .update_connector_response_401_meta import UpdateConnectorResponse401Meta
from .update_connector_response_403 import UpdateConnectorResponse403
from .update_connector_response_403_meta import UpdateConnectorResponse403Meta
from .update_connector_response_404 import UpdateConnectorResponse404
from .update_connector_response_404_meta import UpdateConnectorResponse404Meta
from .update_connector_response_422 import UpdateConnectorResponse422
from .update_connector_response_422_meta import UpdateConnectorResponse422Meta
from .update_connector_response_429 import UpdateConnectorResponse429
from .update_connector_response_429_meta import UpdateConnectorResponse429Meta
from .update_connector_response_500 import UpdateConnectorResponse500
from .update_connector_response_500_meta import UpdateConnectorResponse500Meta
from .update_connector_secret_response_400 import UpdateConnectorSecretResponse400
from .update_connector_secret_response_400_meta import UpdateConnectorSecretResponse400Meta
from .update_connector_secret_response_401 import UpdateConnectorSecretResponse401
from .update_connector_secret_response_401_meta import UpdateConnectorSecretResponse401Meta
from .update_connector_secret_response_403 import UpdateConnectorSecretResponse403
from .update_connector_secret_response_403_meta import UpdateConnectorSecretResponse403Meta
from .update_connector_secret_response_404 import UpdateConnectorSecretResponse404
from .update_connector_secret_response_404_meta import UpdateConnectorSecretResponse404Meta
from .update_connector_secret_response_422 import UpdateConnectorSecretResponse422
from .update_connector_secret_response_422_meta import UpdateConnectorSecretResponse422Meta
from .update_connector_secret_response_429 import UpdateConnectorSecretResponse429
from .update_connector_secret_response_429_meta import UpdateConnectorSecretResponse429Meta
from .update_connector_secret_response_500 import UpdateConnectorSecretResponse500
from .update_connector_secret_response_500_meta import UpdateConnectorSecretResponse500Meta
from .update_secret_request import UpdateSecretRequest
from .update_transfer_response_400 import UpdateTransferResponse400
from .update_transfer_response_400_meta import UpdateTransferResponse400Meta
from .update_transfer_response_401 import UpdateTransferResponse401
from .update_transfer_response_401_meta import UpdateTransferResponse401Meta
from .update_transfer_response_403 import UpdateTransferResponse403
from .update_transfer_response_403_meta import UpdateTransferResponse403Meta
from .update_transfer_response_404 import UpdateTransferResponse404
from .update_transfer_response_404_meta import UpdateTransferResponse404Meta
from .update_transfer_response_422 import UpdateTransferResponse422
from .update_transfer_response_422_meta import UpdateTransferResponse422Meta
from .update_transfer_response_429 import UpdateTransferResponse429
from .update_transfer_response_429_meta import UpdateTransferResponse429Meta
from .update_transfer_response_500 import UpdateTransferResponse500
from .update_transfer_response_500_meta import UpdateTransferResponse500Meta
from .upload_connector_logo_body import UploadConnectorLogoBody
from .upload_connector_logo_response_201 import UploadConnectorLogoResponse201
from .upload_connector_logo_response_400 import UploadConnectorLogoResponse400
from .upload_connector_logo_response_400_meta import UploadConnectorLogoResponse400Meta
from .upload_connector_logo_response_401 import UploadConnectorLogoResponse401
from .upload_connector_logo_response_401_meta import UploadConnectorLogoResponse401Meta
from .upload_connector_logo_response_403 import UploadConnectorLogoResponse403
from .upload_connector_logo_response_403_meta import UploadConnectorLogoResponse403Meta
from .upload_connector_logo_response_404 import UploadConnectorLogoResponse404
from .upload_connector_logo_response_404_meta import UploadConnectorLogoResponse404Meta
from .upload_connector_logo_response_429 import UploadConnectorLogoResponse429
from .upload_connector_logo_response_429_meta import UploadConnectorLogoResponse429Meta
from .upload_connector_logo_response_500 import UploadConnectorLogoResponse500
from .upload_connector_logo_response_500_meta import UploadConnectorLogoResponse500Meta
from .user import User
from .user_type import UserType
from .validate_transfer_response_401 import ValidateTransferResponse401
from .validate_transfer_response_401_meta import ValidateTransferResponse401Meta
from .validate_transfer_response_403 import ValidateTransferResponse403
from .validate_transfer_response_403_meta import ValidateTransferResponse403Meta
from .validate_transfer_response_429 import ValidateTransferResponse429
from .validate_transfer_response_429_meta import ValidateTransferResponse429Meta
from .validate_transfer_response_500 import ValidateTransferResponse500
from .validate_transfer_response_500_meta import ValidateTransferResponse500Meta
from .validate_transfer_update_response_401 import ValidateTransferUpdateResponse401
from .validate_transfer_update_response_401_meta import ValidateTransferUpdateResponse401Meta
from .validate_transfer_update_response_403 import ValidateTransferUpdateResponse403
from .validate_transfer_update_response_403_meta import ValidateTransferUpdateResponse403Meta
from .validate_transfer_update_response_404 import ValidateTransferUpdateResponse404
from .validate_transfer_update_response_404_meta import ValidateTransferUpdateResponse404Meta
from .validate_transfer_update_response_429 import ValidateTransferUpdateResponse429
from .validate_transfer_update_response_429_meta import ValidateTransferUpdateResponse429Meta
from .validate_transfer_update_response_500 import ValidateTransferUpdateResponse500
from .validate_transfer_update_response_500_meta import ValidateTransferUpdateResponse500Meta
from .validation_error import ValidationError
from .validation_errors_response import ValidationErrorsResponse

__all__ = (
    "AbstractResponse",
    "AvailableSourcesResponse",
    "Backfill",
    "BackfillResponse",
    "BackfillResponseMeta",
    "BackfillStatus",
    "ChangeTransferStateRequest",
    "ChangeTransferStateRequestTransferState",
    "ChangeTransferStateResponse400",
    "ChangeTransferStateResponse400Meta",
    "ChangeTransferStateResponse401",
    "ChangeTransferStateResponse401Meta",
    "ChangeTransferStateResponse403",
    "ChangeTransferStateResponse403Meta",
    "ChangeTransferStateResponse404",
    "ChangeTransferStateResponse404Meta",
    "ChangeTransferStateResponse429",
    "ChangeTransferStateResponse429Meta",
    "ChangeTransferStateResponse500",
    "ChangeTransferStateResponse500Meta",
    "CloseLoginLinkResponse401",
    "CloseLoginLinkResponse401Meta",
    "CloseLoginLinkResponse404",
    "CloseLoginLinkResponse404Error",
    "CloseLoginLinkResponse422",
    "CloseLoginLinkResponse422Meta",
    "CloseLoginLinkResponse429",
    "CloseLoginLinkResponse429Meta",
    "CloseLoginLinkResponse500",
    "CloseLoginLinkResponse500Error",
    "Connector",
    "ConnectorConfiguration",
    "ConnectorConfigurationConfigurationJson",
    "ConnectorWithConfiguration",
    "CreateBackfillRequest",
    "CreateBackfillResponse400",
    "CreateBackfillResponse400Meta",
    "CreateBackfillResponse401",
    "CreateBackfillResponse401Meta",
    "CreateBackfillResponse403",
    "CreateBackfillResponse403Meta",
    "CreateBackfillResponse422",
    "CreateBackfillResponse422Meta",
    "CreateBackfillResponse429",
    "CreateBackfillResponse429Meta",
    "CreateBackfillResponse500",
    "CreateBackfillResponse500Meta",
    "CreateConnectorBody",
    "CreateConnectorResponse401",
    "CreateConnectorResponse401Meta",
    "CreateConnectorResponse403",
    "CreateConnectorResponse403Meta",
    "CreateConnectorResponse404",
    "CreateConnectorResponse404Meta",
    "CreateConnectorResponse429",
    "CreateConnectorResponse429Meta",
    "CreateConnectorResponse500",
    "CreateConnectorResponse500Meta",
    "CreateConnectorSecretResponse201",
    "CreateConnectorSecretResponse400",
    "CreateConnectorSecretResponse400Meta",
    "CreateConnectorSecretResponse401",
    "CreateConnectorSecretResponse401Meta",
    "CreateConnectorSecretResponse403",
    "CreateConnectorSecretResponse403Meta",
    "CreateConnectorSecretResponse404",
    "CreateConnectorSecretResponse404Meta",
    "CreateConnectorSecretResponse409",
    "CreateConnectorSecretResponse409Meta",
    "CreateConnectorSecretResponse422",
    "CreateConnectorSecretResponse422Meta",
    "CreateConnectorSecretResponse429",
    "CreateConnectorSecretResponse429Meta",
    "CreateConnectorSecretResponse500",
    "CreateConnectorSecretResponse500Meta",
    "CreateDataSourceConnectionRequest",
    "CreateDataSourceConnectionResponse",
    "CreateDataSourceConnectionResponse400",
    "CreateDataSourceConnectionResponse400Meta",
    "CreateDataSourceConnectionResponse401",
    "CreateDataSourceConnectionResponse401Meta",
    "CreateDataSourceConnectionResponse403",
    "CreateDataSourceConnectionResponse403Meta",
    "CreateDataSourceConnectionResponse422",
    "CreateDataSourceConnectionResponse422Meta",
    "CreateDataSourceConnectionResponse429",
    "CreateDataSourceConnectionResponse429Meta",
    "CreateDataSourceConnectionResponse500",
    "CreateDataSourceConnectionResponse500Meta",
    "CreateLoginLinkBody",
    "CreateLoginLinkResponse401",
    "CreateLoginLinkResponse401Meta",
    "CreateLoginLinkResponse403",
    "CreateLoginLinkResponse403Error",
    "CreateLoginLinkResponse422",
    "CreateLoginLinkResponse422Meta",
    "CreateLoginLinkResponse429",
    "CreateLoginLinkResponse429Meta",
    "CreateLoginLinkResponse500",
    "CreateLoginLinkResponse500Meta",
    "CreateSecretRequest",
    "CreateTransferResponse400",
    "CreateTransferResponse400Meta",
    "CreateTransferResponse401",
    "CreateTransferResponse401Meta",
    "CreateTransferResponse403",
    "CreateTransferResponse403Meta",
    "CreateTransferResponse409",
    "CreateTransferResponse409Meta",
    "CreateTransferResponse422",
    "CreateTransferResponse422Meta",
    "CreateTransferResponse429",
    "CreateTransferResponse429Meta",
    "CreateTransferResponse500",
    "CreateTransferResponse500Meta",
    "DataQuery",
    "DataQueryDsAccountsType2",
    "DataQueryFieldsType2Item",
    "DataQuerySettings",
    "DataResponse",
    "DataResponseMeta",
    "DataResponseMetaPaginate",
    "DataResponseMetaQuery",
    "DataResponseMetaQueryFieldsItem",
    "DataResponseMetaQuerySettings",
    "DataResponseMetaResult",
    "DataSource",
    "DataSourceConnection",
    "DatasourceDetails",
    "DatasourceDetailsAccountLabelsType0",
    "DatasourceDetailsCategoriesItem",
    "DatasourceDetailsResponse",
    "DatasourceDetailsResponseMeta",
    "DatasourceDetailsStatus",
    "DataSourceInfo",
    "DataSourceLogin",
    "DataSourceLoginType",
    "DatasourceOption",
    "DatasourceReportType",
    "DatasourceSetting",
    "DatasourceSettingContext",
    "DatasourceSettingType",
    "DataSourceType",
    "DeleteConnectorResponse400",
    "DeleteConnectorResponse400Meta",
    "DeleteConnectorResponse401",
    "DeleteConnectorResponse401Meta",
    "DeleteConnectorResponse403",
    "DeleteConnectorResponse403Meta",
    "DeleteConnectorResponse404",
    "DeleteConnectorResponse404Meta",
    "DeleteConnectorResponse429",
    "DeleteConnectorResponse429Meta",
    "DeleteConnectorResponse500",
    "DeleteConnectorResponse500Meta",
    "DeleteConnectorSecretResponse401",
    "DeleteConnectorSecretResponse401Meta",
    "DeleteConnectorSecretResponse403",
    "DeleteConnectorSecretResponse403Meta",
    "DeleteConnectorSecretResponse404",
    "DeleteConnectorSecretResponse404Meta",
    "DeleteConnectorSecretResponse429",
    "DeleteConnectorSecretResponse429Meta",
    "DeleteConnectorSecretResponse500",
    "DeleteConnectorSecretResponse500Meta",
    "DeleteTransferResponse401",
    "DeleteTransferResponse401Meta",
    "DeleteTransferResponse403",
    "DeleteTransferResponse403Meta",
    "DeleteTransferResponse404",
    "DeleteTransferResponse404Meta",
    "DeleteTransferResponse429",
    "DeleteTransferResponse429Meta",
    "DeleteTransferResponse500",
    "DeleteTransferResponse500Meta",
    "DestinationTypeSettings",
    "DestinationTypeSettingsAuthMethodsItem",
    "DestinationTypeSettingsSettingsItem",
    "Error",
    "ErrorResponse",
    "ErrorResponseMeta",
    "GetAccountsJson",
    "GetAccountsResponse200",
    "GetAccountsResponse200DataItem",
    "GetAccountsResponse200DataItemAccountsItem",
    "GetAccountsResponse200Meta",
    "GetAccountsResponse200MetaQuery",
    "GetAccountsResponse400",
    "GetAccountsResponse400Meta",
    "GetAccountsResponse401",
    "GetAccountsResponse401Meta",
    "GetAccountsResponse403",
    "GetAccountsResponse403Meta",
    "GetAccountsResponse422",
    "GetAccountsResponse422Meta",
    "GetAccountsResponse429",
    "GetAccountsResponse429Meta",
    "GetAccountsResponse500",
    "GetAccountsResponse500Meta",
    "GetAvailableSourcesResponse401",
    "GetAvailableSourcesResponse401Meta",
    "GetAvailableSourcesResponse403",
    "GetAvailableSourcesResponse403Meta",
    "GetAvailableSourcesResponse429",
    "GetAvailableSourcesResponse429Meta",
    "GetAvailableSourcesResponse500",
    "GetAvailableSourcesResponse500Meta",
    "GetBackfillByIdResponse401",
    "GetBackfillByIdResponse401Meta",
    "GetBackfillByIdResponse403",
    "GetBackfillByIdResponse403Meta",
    "GetBackfillByIdResponse404",
    "GetBackfillByIdResponse404Meta",
    "GetBackfillByIdResponse429",
    "GetBackfillByIdResponse429Meta",
    "GetBackfillByIdResponse500",
    "GetBackfillByIdResponse500Meta",
    "GetConnectorLogoResponse200",
    "GetConnectorLogoResponse401",
    "GetConnectorLogoResponse401Meta",
    "GetConnectorLogoResponse403",
    "GetConnectorLogoResponse403Meta",
    "GetConnectorLogoResponse404",
    "GetConnectorLogoResponse404Meta",
    "GetConnectorLogoResponse429",
    "GetConnectorLogoResponse429Meta",
    "GetConnectorLogoResponse500",
    "GetConnectorLogoResponse500Meta",
    "GetConnectorLogResponse401",
    "GetConnectorLogResponse401Meta",
    "GetConnectorLogResponse403",
    "GetConnectorLogResponse403Meta",
    "GetConnectorLogResponse404",
    "GetConnectorLogResponse404Meta",
    "GetConnectorLogResponse429",
    "GetConnectorLogResponse429Meta",
    "GetConnectorLogResponse500",
    "GetConnectorLogResponse500Meta",
    "GetConnectorResponse400",
    "GetConnectorResponse400Meta",
    "GetConnectorResponse401",
    "GetConnectorResponse401Meta",
    "GetConnectorResponse403",
    "GetConnectorResponse403Meta",
    "GetConnectorResponse404",
    "GetConnectorResponse404Meta",
    "GetConnectorResponse429",
    "GetConnectorResponse429Meta",
    "GetConnectorResponse500",
    "GetConnectorResponse500Meta",
    "GetDataResponse400",
    "GetDataResponse400Meta",
    "GetDataResponse401",
    "GetDataResponse401Meta",
    "GetDataResponse403",
    "GetDataResponse403Meta",
    "GetDataResponse422",
    "GetDataResponse422Meta",
    "GetDataResponse429",
    "GetDataResponse429Meta",
    "GetDataResponse500",
    "GetDataResponse500Meta",
    "GetDatasourceDetailsResponse400",
    "GetDatasourceDetailsResponse400Meta",
    "GetDatasourceDetailsResponse401",
    "GetDatasourceDetailsResponse401Meta",
    "GetDatasourceDetailsResponse404",
    "GetDatasourceDetailsResponse404Meta",
    "GetDatasourceDetailsResponse429",
    "GetDatasourceDetailsResponse429Meta",
    "GetDatasourceDetailsResponse500",
    "GetDatasourceDetailsResponse500Meta",
    "GetDataSourceLoginResponse200",
    "GetDataSourceLoginResponse401",
    "GetDataSourceLoginResponse401Meta",
    "GetDataSourceLoginResponse404",
    "GetDataSourceLoginResponse404Error",
    "GetDataSourceLoginResponse422",
    "GetDataSourceLoginResponse422Meta",
    "GetDataSourceLoginResponse429",
    "GetDataSourceLoginResponse429Meta",
    "GetDataSourceLoginResponse500",
    "GetDataSourceLoginResponse500Error",
    "GetLatestBackfillResponse401",
    "GetLatestBackfillResponse401Meta",
    "GetLatestBackfillResponse403",
    "GetLatestBackfillResponse403Meta",
    "GetLatestBackfillResponse429",
    "GetLatestBackfillResponse429Meta",
    "GetLatestBackfillResponse500",
    "GetLatestBackfillResponse500Meta",
    "GetLoginLinkResponse401",
    "GetLoginLinkResponse401Meta",
    "GetLoginLinkResponse404",
    "GetLoginLinkResponse404Error",
    "GetLoginLinkResponse422",
    "GetLoginLinkResponse422Meta",
    "GetLoginLinkResponse429",
    "GetLoginLinkResponse429Meta",
    "GetLoginLinkResponse500",
    "GetLoginLinkResponse500Meta",
    "GetTransferOptionsResponse401",
    "GetTransferOptionsResponse401Meta",
    "GetTransferOptionsResponse403",
    "GetTransferOptionsResponse403Meta",
    "GetTransferOptionsResponse429",
    "GetTransferOptionsResponse429Meta",
    "GetTransferOptionsResponse500",
    "GetTransferOptionsResponse500Meta",
    "GetTransferResponse401",
    "GetTransferResponse401Meta",
    "GetTransferResponse403",
    "GetTransferResponse403Meta",
    "GetTransferResponse404",
    "GetTransferResponse404Meta",
    "GetTransferResponse429",
    "GetTransferResponse429Meta",
    "GetTransferResponse500",
    "GetTransferResponse500Meta",
    "GetTransferRunResponse401",
    "GetTransferRunResponse401Meta",
    "GetTransferRunResponse403",
    "GetTransferRunResponse403Meta",
    "GetTransferRunResponse404",
    "GetTransferRunResponse404Meta",
    "GetTransferRunResponse429",
    "GetTransferRunResponse429Meta",
    "GetTransferRunResponse500",
    "GetTransferRunResponse500Meta",
    "ListConnectorLogsResponse200",
    "ListConnectorLogsResponse400",
    "ListConnectorLogsResponse400Meta",
    "ListConnectorLogsResponse401",
    "ListConnectorLogsResponse401Meta",
    "ListConnectorLogsResponse403",
    "ListConnectorLogsResponse403Meta",
    "ListConnectorLogsResponse429",
    "ListConnectorLogsResponse429Meta",
    "ListConnectorLogsResponse500",
    "ListConnectorLogsResponse500Meta",
    "ListConnectorSecretsResponse200",
    "ListConnectorSecretsResponse401",
    "ListConnectorSecretsResponse401Meta",
    "ListConnectorSecretsResponse403",
    "ListConnectorSecretsResponse403Meta",
    "ListConnectorSecretsResponse404",
    "ListConnectorSecretsResponse404Meta",
    "ListConnectorSecretsResponse429",
    "ListConnectorSecretsResponse429Meta",
    "ListConnectorSecretsResponse500",
    "ListConnectorSecretsResponse500Meta",
    "ListConnectorsResponse200",
    "ListConnectorsResponse401",
    "ListConnectorsResponse401Meta",
    "ListConnectorsResponse403",
    "ListConnectorsResponse403Meta",
    "ListConnectorsResponse429",
    "ListConnectorsResponse429Meta",
    "ListConnectorsResponse500",
    "ListConnectorsResponse500Meta",
    "ListDataSourceLoginsResponse200",
    "ListDataSourceLoginsResponse401",
    "ListDataSourceLoginsResponse401Meta",
    "ListDataSourceLoginsResponse422",
    "ListDataSourceLoginsResponse422Meta",
    "ListDataSourceLoginsResponse429",
    "ListDataSourceLoginsResponse429Meta",
    "ListDataSourceLoginsResponse500",
    "ListDataSourceLoginsResponse500Error",
    "ListIncompleteBackfillsResponse200",
    "ListIncompleteBackfillsResponse401",
    "ListIncompleteBackfillsResponse401Meta",
    "ListIncompleteBackfillsResponse403",
    "ListIncompleteBackfillsResponse403Meta",
    "ListIncompleteBackfillsResponse429",
    "ListIncompleteBackfillsResponse429Meta",
    "ListIncompleteBackfillsResponse500",
    "ListIncompleteBackfillsResponse500Meta",
    "ListLoginLinksResponse200",
    "ListLoginLinksResponse401",
    "ListLoginLinksResponse401Meta",
    "ListLoginLinksResponse422",
    "ListLoginLinksResponse422Meta",
    "ListLoginLinksResponse429",
    "ListLoginLinksResponse429Meta",
    "ListLoginLinksResponse500",
    "ListLoginLinksResponse500Meta",
    "ListTransferRunsResponse401",
    "ListTransferRunsResponse401Meta",
    "ListTransferRunsResponse403",
    "ListTransferRunsResponse403Meta",
    "ListTransferRunsResponse429",
    "ListTransferRunsResponse429Meta",
    "ListTransferRunsResponse500",
    "ListTransferRunsResponse500Meta",
    "ListTransferRunsSortDirection",
    "ListTransferRunsSortField",
    "ListTransfersResponse401",
    "ListTransfersResponse401Meta",
    "ListTransfersResponse403",
    "ListTransfersResponse403Meta",
    "ListTransfersResponse429",
    "ListTransfersResponse429Meta",
    "ListTransfersResponse500",
    "ListTransfersResponse500Meta",
    "LogEntry",
    "LoginLink",
    "LoginLinkResponse",
    "LoginLinkResponseMeta",
    "LoginLinkStatusCode",
    "Meta",
    "QueryDetails",
    "ResponseMeta",
    "Secret",
    "TransferAccount",
    "TransferBackfillRunError",
    "TransferConfigurationRequest",
    "TransferConfigurationResponse",
    "TransferConfigurationResponseDataSource",
    "TransferConfigurationResponseLicense",
    "TransferConfigurationResponseLicenseFeatures",
    "TransferConfigurationResponseNotificationRecipientsType0Item",
    "TransferCreatedEnvelope",
    "TransferCreatedResponse",
    "TransferDataSourceSetting",
    "TransferDestination",
    "TransferDestinationDetailsItem",
    "TransferInfoResponse",
    "TransferInfoResponseBackfillType0",
    "TransferInfoResponseDataSourceType0",
    "TransferInfoResponseDestinationType0",
    "TransferListResponse",
    "TransferOptionsResponse",
    "TransferOptionsResponseAccountsItem",
    "TransferOptionsResponseDataSource",
    "TransferOptionsResponseDataSourceSettingsItem",
    "TransferOptionsResponseLicense",
    "TransferOptionsResponseLoginsItem",
    "TransferOptionsResponseScheduleOptionsItem",
    "TransferOptionsResponseSchemasItem",
    "TransferOptionsResponseSegmentsItem",
    "TransferRunDetail",
    "TransferRunDetailResponse",
    "TransferRunItem",
    "TransferRunItemType",
    "TransferRunListResponse",
    "TransferSchedule",
    "TransferScheduleRunInterval",
    "TransferSegment",
    "TransferStateUpdateResponse",
    "TransferUpdatedResponse",
    "UpdateBackfillStatusBody",
    "UpdateBackfillStatusBodyStatus",
    "UpdateBackfillStatusResponse400",
    "UpdateBackfillStatusResponse400Meta",
    "UpdateBackfillStatusResponse401",
    "UpdateBackfillStatusResponse401Meta",
    "UpdateBackfillStatusResponse403",
    "UpdateBackfillStatusResponse403Meta",
    "UpdateBackfillStatusResponse404",
    "UpdateBackfillStatusResponse404Meta",
    "UpdateBackfillStatusResponse422",
    "UpdateBackfillStatusResponse422Meta",
    "UpdateBackfillStatusResponse429",
    "UpdateBackfillStatusResponse429Meta",
    "UpdateBackfillStatusResponse500",
    "UpdateBackfillStatusResponse500Meta",
    "UpdateConnectorRequest",
    "UpdateConnectorRequestConfiguration",
    "UpdateConnectorRequestConfigurationConfigurationJson",
    "UpdateConnectorRequestConnector",
    "UpdateConnectorResponse400",
    "UpdateConnectorResponse400Meta",
    "UpdateConnectorResponse401",
    "UpdateConnectorResponse401Meta",
    "UpdateConnectorResponse403",
    "UpdateConnectorResponse403Meta",
    "UpdateConnectorResponse404",
    "UpdateConnectorResponse404Meta",
    "UpdateConnectorResponse422",
    "UpdateConnectorResponse422Meta",
    "UpdateConnectorResponse429",
    "UpdateConnectorResponse429Meta",
    "UpdateConnectorResponse500",
    "UpdateConnectorResponse500Meta",
    "UpdateConnectorSecretResponse400",
    "UpdateConnectorSecretResponse400Meta",
    "UpdateConnectorSecretResponse401",
    "UpdateConnectorSecretResponse401Meta",
    "UpdateConnectorSecretResponse403",
    "UpdateConnectorSecretResponse403Meta",
    "UpdateConnectorSecretResponse404",
    "UpdateConnectorSecretResponse404Meta",
    "UpdateConnectorSecretResponse422",
    "UpdateConnectorSecretResponse422Meta",
    "UpdateConnectorSecretResponse429",
    "UpdateConnectorSecretResponse429Meta",
    "UpdateConnectorSecretResponse500",
    "UpdateConnectorSecretResponse500Meta",
    "UpdateSecretRequest",
    "UpdateTransferResponse400",
    "UpdateTransferResponse400Meta",
    "UpdateTransferResponse401",
    "UpdateTransferResponse401Meta",
    "UpdateTransferResponse403",
    "UpdateTransferResponse403Meta",
    "UpdateTransferResponse404",
    "UpdateTransferResponse404Meta",
    "UpdateTransferResponse422",
    "UpdateTransferResponse422Meta",
    "UpdateTransferResponse429",
    "UpdateTransferResponse429Meta",
    "UpdateTransferResponse500",
    "UpdateTransferResponse500Meta",
    "UploadConnectorLogoBody",
    "UploadConnectorLogoResponse201",
    "UploadConnectorLogoResponse400",
    "UploadConnectorLogoResponse400Meta",
    "UploadConnectorLogoResponse401",
    "UploadConnectorLogoResponse401Meta",
    "UploadConnectorLogoResponse403",
    "UploadConnectorLogoResponse403Meta",
    "UploadConnectorLogoResponse404",
    "UploadConnectorLogoResponse404Meta",
    "UploadConnectorLogoResponse429",
    "UploadConnectorLogoResponse429Meta",
    "UploadConnectorLogoResponse500",
    "UploadConnectorLogoResponse500Meta",
    "User",
    "UserType",
    "ValidateTransferResponse401",
    "ValidateTransferResponse401Meta",
    "ValidateTransferResponse403",
    "ValidateTransferResponse403Meta",
    "ValidateTransferResponse429",
    "ValidateTransferResponse429Meta",
    "ValidateTransferResponse500",
    "ValidateTransferResponse500Meta",
    "ValidateTransferUpdateResponse401",
    "ValidateTransferUpdateResponse401Meta",
    "ValidateTransferUpdateResponse403",
    "ValidateTransferUpdateResponse403Meta",
    "ValidateTransferUpdateResponse404",
    "ValidateTransferUpdateResponse404Meta",
    "ValidateTransferUpdateResponse429",
    "ValidateTransferUpdateResponse429Meta",
    "ValidateTransferUpdateResponse500",
    "ValidateTransferUpdateResponse500Meta",
    "ValidationError",
    "ValidationErrorsResponse",
)
