from enum import Enum


class DatasourceDetailsCategoriesItem(str, Enum):
    AD_VERIFICATION = "AD_VERIFICATION"
    AFFILIATE = "AFFILIATE"
    ANALYTICS = "ANALYTICS"
    BRAND_REPUTATION = "BRAND_REPUTATION"
    CRM_SALES = "CRM_SALES"
    DATA_WAREHOUSES = "DATA_WAREHOUSES"
    DSP = "DSP"
    ECOMMERCE = "ECOMMERCE"
    FILES = "FILES"
    MARKETING_ATTRIBUTION = "MARKETING_ATTRIBUTION"
    MARKETING_AUTOMATION = "MARKETING_AUTOMATION"
    MOBILE = "MOBILE"
    OTHER = "OTHER"
    PAID_MEDIA = "PAID_MEDIA"
    PAYMENTS = "PAYMENTS"
    RETAIL_MEDIA = "RETAIL_MEDIA"
    SEARCH = "SEARCH"
    SEO = "SEO"
    SOCIAL_MEDIA = "SOCIAL_MEDIA"

    def __str__(self) -> str:
        return str(self.value)
